name: manim_shaders
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.7
  - pip
  - pip:
    - pyreadline
    - matplotlib
    - mapbox-earcut
    - moderngl_window
    - screeninfo
    - argparse
    - colour
    - numpy
    - Pillow
    - progressbar
    - scipy
    - sympy
    - tqdm
    - moderngl
    - pydub
    - pyyaml
    - validators
    - ipython
    - PyOpenGL
    - pycairo

