name: docs_test

on: 
  pull_request:
    paths:
      - 'docs/**'

jobs:
  docs_test:
    runs-on: ubuntu-latest
    name: Test document for pull requests

    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Install sphinx and manim env
      run: |
        pip3 install --upgrade pip
        sudo apt install python3-setuptools
        pip3 install -r docs/requirements.txt
        pip3 install -r requirements.txt
    
    - name: Build document with Sphinx
      run: |
        cd docs
        export PATH="$PATH:/home/runner/.local/bin"
        export SPHINXBUILD="python3 -m sphinx"
        make html